In [17]:
import pandas as pd
import numpy as np
import math

In [3]:
df = pd.read_csv("C:\\Users\\Prajwal Mahajan\\Downloads\\Datasets\\IRIS.csv")

In [9]:
x = df.iloc[:,0:4].values

In [12]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [15]:
def dist(a1,b1,c1,d1,a2,b2,c2,d2):
    return np.sqrt((a1-a2)**2+(b1-b2)**2+(c1-c2)**2+(d1-d2)**2)

In [21]:
def returncluster(m1,m2,m3,a,b,c,d):
    d1 = dist(m1[0],m1[1],m1[2],m1[3],a,b,c,d)
    d2 = dist(m2[0],m2[1],m2[2],m2[3],a,b,c,d)
    d3 = dist(m3[0],m3[1],m3[2],m3[3],a,b,c,d)

    if d1<d2 and d1<d3:
        return 1
    elif d2<d3 and d2<d1:
        return 2
    else:
        return 3

In [25]:
m1=[4.4,2.9,1.4,0.2]
m2=[5.9,3.2,4.8,1.8]
m3=[7.9,3.8,6.4,2]
itr = 1
for j in range(1,11):
    c1=[]
    c2=[]
    c3=[]
    for i in range(0,len(x)):
        cluster_no = returncluster(m1,m2,m3,x[i][0],x[i][1],x[i][2],x[i][3])
        point = [x[i][0],x[i][1],x[i][2],x[i][3]]
        if cluster_no == 1:
            c1.append(point)
        elif cluster_no == 2:
            c2.append(point)
        else:
            c3.append(point)
    print("Iteration: ",itr)
    print("m1:",m1,"m2:",m2,"m3:",m3)
    
    m1_old = m1
    m1=[]
    m2_old = m2
    m2=[]
    m3_old = m3
    m3=[]

    m1 = np.mean(c1,axis=0)
    m2 = np.mean(c2,axis=0)
    m3 = np.mean(c3,axis=0)
    
    print("c1:",c1,"c2:",c2,"c3:",c3)
    print("m1:",m1,"m2:",m2,"m3:",m3)
    print("")
    itr+=1
        
    

Iteration:  1
m1: [4.4, 2.9, 1.4, 0.2] m2: [5.9, 3.2, 4.8, 1.8] m3: [7.9, 3.8, 6.4, 2]
c1: [[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [4.6, 3.4, 1.4, 0.3], [5.0, 3.4, 1.5, 0.2], [4.4, 2.9, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.4, 3.7, 1.5, 0.2], [4.8, 3.4, 1.6, 0.2], [4.8, 3.0, 1.4, 0.1], [4.3, 3.0, 1.1, 0.1], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [4.6, 3.6, 1.0, 0.2], [5.1, 3.3, 1.7, 0.5], [4.8, 3.4, 1.9, 0.2], [5.0, 3.0, 1.6, 0.2], [5.0, 3.4, 1.6, 0.4], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [4.7, 3.2, 1.6, 0.2], [4.8, 3.1, 1.6, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.0, 3.2, 1.2, 0.2], [5.5, 3.5, 1.3, 0.2], [4.9, 3.1, 1.5, 0.1], [4.4, 3.0, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.0, 3.5, 1.3, 0.3], [4.5, 